#Sun Mar 01 06:37:30 UTC 2026

micronaut:
  application:
    name: micronaut-meeting-room-booking
  server:
    port: 3000
  openapi:
    views:
      spec: "scalar.enabled=true"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      scalar:
        paths: classpath:META-INF/swagger/views/scalar
        mapping: /scalar/**

flyway:
  datasources:
    default:
      enabled: true
      # clean-schema: true
    

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/micronaut_meeting_room_booking_api